# Generated by Django 5.2.12 on 2026-03-09 13:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. A1, A2, B1', max_length=5, unique=True)),
                ('name', models.CharField(help_text='e.g. Breakthrough, Waystage', max_length=100)),
                ('order', models.PositiveIntegerField(help_text='1=A1 through 6=C2', unique=True)),
                ('description', models.TextField(blank=True, help_text='General can-do summary')),
                ('min_score', models.FloatField(default=0.0, help_text='Minimum composite score for this level (0-10)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('max_score', models.FloatField(default=10.0, help_text='Maximum composite score for this level (0-10)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
            ],
            options={
                'verbose_name': 'CEFR Level',
                'verbose_name_plural': 'CEFR Levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('instruction_template', models.TextField(blank=True, help_text='Default instruction shown to learner')),
                ('is_auto_gradable', models.BooleanField(default=True, help_text='Can the system grade this automatically?')),
                ('response_format', models.CharField(choices=[('single_choice', 'Single Choice (MCQ)'), ('true_false', 'True / False'), ('text_input', 'Short Text Input'), ('long_text', 'Long Text (Essay / Letter)'), ('audio', 'Audio Recording'), ('ordering', 'Ordering / Sequencing'), ('matching', 'Matching Pairs')], default='single_choice', max_length=20)),
            ],
            options={
                'verbose_name': 'Question Type',
                'verbose_name_plural': 'Question Types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('native_language', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_cefr_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='assessment.cefrlevel')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('placement', 'Placement Test'), ('practice', 'Practice'), ('skill_test', 'Skill Test')], default='practice', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('max_possible_score', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='assessment.candidate')),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_current', to='assessment.cefrlevel')),
                ('final_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_final', to='assessment.cefrlevel')),
                ('starting_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_started', to='assessment.cefrlevel')),
                ('skill_focus', models.ForeignKey(blank=True, help_text='NULL = mixed / all skills', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='assessment.skill')),
            ],
            options={
                'verbose_name': 'Assessment Session',
                'verbose_name_plural': 'Assessment Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(help_text='e.g. A1-READ-MCQ-001', max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('instruction_text', models.TextField(blank=True, help_text='Instructions for the learner')),
                ('content_text', models.TextField(blank=True, help_text='Reading passage, listening script, scenario')),
                ('question_text', models.TextField(help_text='The actual question or prompt')),
                ('media_url', models.URLField(blank=True, help_text='Image / audio / video URL', max_length=500)),
                ('media_type', models.CharField(blank=True, choices=[('', 'None'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='', max_length=10)),
                ('correct_answer', models.TextField(blank=True, help_text='Correct answer for auto-gradable types')),
                ('sample_answer', models.TextField(blank=True, help_text='Model answer for subjective types')),
                ('explanation', models.TextField(blank=True, help_text='Why the correct answer is correct')),
                ('difficulty', models.PositiveIntegerField(default=1, help_text='1=easy, 2=medium, 3=hard within level')),
                ('points', models.PositiveIntegerField(default=1)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cefr_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.cefrlevel')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.questiontype')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.skill')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['cefr_level__order', 'skill__order', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='OrderingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_position', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_items', to='assessment.question')),
            ],
            options={
                'verbose_name': 'Ordering Item',
                'verbose_name_plural': 'Ordering Items',
                'ordering': ['correct_position'],
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.TextField()),
                ('right_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='assessment.question')),
            ],
            options={
                'verbose_name': 'Matching Pair',
                'verbose_name_plural': 'Matching Pairs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='A, B, C, D', max_length=5)),
                ('text', models.TextField()),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment.question')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, help_text='Typed answer')),
                ('response_data', models.JSONField(blank=True, help_text='Structured data for matching/ordering', null=True)),
                ('audio_file_path', models.CharField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(help_text='NULL = not yet graded', null=True)),
                ('score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=1)),
                ('feedback', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='assessment.questionoption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.assessmentsession')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'ordering': ['responded_at'],
            },
        ),
        migrations.AddField(
            model_name='questiontype',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='question_types', to='assessment.skill'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cefr_levels', models.ManyToManyField(blank=True, related_name='topics', to='assessment.cefrlevel')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.topic'),
        ),
        migrations.CreateModel(
            name='LevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False)),
                ('completion_percentage', models.FloatField(default=0)),
                ('best_score', models.FloatField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='assessment.candidate')),
                ('cefr_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='assessment.cefrlevel')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='assessment.skill')),
            ],
            options={
                'verbose_name': 'Level Progress',
                'verbose_name_plural': 'Level Progress',
                'unique_together': {('candidate', 'cefr_level', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='SkillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('max_possible_score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('cefr_level_achieved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_scores', to='assessment.cefrlevel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_scores', to='assessment.assessmentsession')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_scores', to='assessment.skill')),
            ],
            options={
                'verbose_name': 'Skill Score',
                'verbose_name_plural': 'Skill Scores',
                'unique_together': {('session', 'skill')},
            },
        ),
    ]
