# Generated by Django 5.2.12 on 2026-03-15 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='suggested_unit_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnswerSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='One acceptable answer sample')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Optional anchor keywords')),
                ('weight', models.FloatField(default=1.0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_samples', to='assessment.question')),
            ],
            options={
                'verbose_name': 'Answer Sample',
                'verbose_name_plural': 'Answer Samples',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CEFRSubLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. A1.1, A2.5', max_length=10, unique=True)),
                ('unit_order', models.PositiveIntegerField(help_text='Unit number within level')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cefr_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublevels', to='assessment.cefrlevel')),
            ],
            options={
                'verbose_name': 'CEFR Sublevel',
                'verbose_name_plural': 'CEFR Sublevels',
                'ordering': ['cefr_level__order', 'unit_order'],
                'unique_together': {('cefr_level', 'unit_order')},
            },
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='current_sublevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_current', to='assessment.cefrsublevel'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='final_sublevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_final', to='assessment.cefrsublevel'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='starting_sublevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_started', to='assessment.cefrsublevel'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_sublevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='assessment.cefrsublevel'),
        ),
        migrations.AddField(
            model_name='question',
            name='sublevel',
            field=models.ForeignKey(blank=True, help_text='Unit-based CEFR sublevel (e.g., A1.3)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='assessment.cefrsublevel'),
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=1)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='assessment.candidate')),
                ('cefr_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='assessment.cefrlevel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='assessment.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='assessment.assessmentsession')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='assessment.skill')),
                ('sublevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_attempts', to='assessment.cefrsublevel')),
            ],
            options={
                'verbose_name': 'User Attempt',
                'verbose_name_plural': 'User Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('mastery_score', models.FloatField(default=0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='assessment.candidate')),
                ('cefr_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='assessment.cefrlevel')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='assessment.skill')),
                ('sublevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='assessment.cefrsublevel')),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
                'ordering': ['candidate__name', 'cefr_level__order', 'sublevel__unit_order', 'skill__order'],
                'unique_together': {('candidate', 'sublevel', 'skill')},
            },
        ),
    ]
