# Generated by Django 5.2.12 on 2026-03-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_seed_structured_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(help_text='1=Beginner, 2=Intermediate, 3=Advanced', unique=True)),
                ('grade_band', models.CharField(blank=True, help_text="e.g. '4-5', '6-7', '8-9'", max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Difficulty Tier',
                'verbose_name_plural': 'Difficulty Tiers',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list, help_text='List of accepted answer strings for subjective types (used instead of AnswerSample for text matching)'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_matching_mode',
            field=models.CharField(choices=[('exact', 'Exact Match'), ('normalized', 'Normalised (strip + lowercase)'), ('keyword', 'Keyword Overlap'), ('multi_accepted', 'Multiple Accepted Answers'), ('ai_graded', 'AI Graded')], default='normalized', help_text="How the engine should compare the learner's response to the correct answer", max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='is_case_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='speaking_topic',
            field=models.TextField(blank=True, help_text='Explicit topic or prompt for speaking questions (always sent to frontend)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Correct answer for objective (auto-gradable) types'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Why the correct answer is correct (shown after attempt)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sample_answer',
            field=models.TextField(blank=True, help_text='Legacy: pipe-separated model answers for subjective types'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='response_format',
            field=models.CharField(choices=[('single_choice', 'Single Choice (MCQ)'), ('true_false', 'True / False'), ('text_input', 'Short Text Input'), ('long_text', 'Long Text (Essay / Letter)'), ('audio', 'Audio Recording'), ('ordering', 'Ordering / Sequencing'), ('matching', 'Matching Pairs'), ('dictation', 'Dictation'), ('sentence_build', 'Sentence Building'), ('error_correction', 'Error Correction'), ('picture_prompt', 'Picture-Based Prompt')], default='single_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_tier',
            field=models.ForeignKey(blank=True, help_text='Beginner / Intermediate / Advanced grade band', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='assessment.difficultytier'),
        ),
    ]
